import { Invoice } from './classes/Invoice.js';
import { Payment } from './classes/Payment.js';
import { ListTemplate } from './classes/ListTemplate.js';
const form = document.querySelector('.new-item-form');
const type = document.querySelector('#type');
const start = document.querySelector('#start');
const tofrom = document.querySelector('#tofrom');
const details = document.querySelector('#details');
const amount = document.querySelector('#amount');
const ul = document.querySelector('ul');
const list = new ListTemplate(ul);
form.addEventListener('submit', (e) => {
    e.preventDefault();
    let position = start.checked ? 'start' : 'end';
    let values;
    values = [tofrom.value, details.value, amount.valueAsNumber];
    let doc;
    doc = type.value === 'invoice' ? new Invoice(...values) : new Payment(...values);
    list.render(doc, type.value, position);
});
